#! /bin/bash
#
#$Author: ee364f03 $
#$Date: 2015-01-14 10:07:44 -0500 (Wed, 14 Jan 2015) $
#$Revision: 71728 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S15/students/ee364f03/Lab00/Script1 $
Num_Of_Param=$#
Param_Values=$@
echo "The program received $Num_Of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0

