#! /bin/bash
#
#$Author: ee364f03 $
#$Date: 2015-01-14 10:24:38 -0500 (Wed, 14 Jan 2015) $
#$Revision: 71801 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S15/students/ee364f03/Lab00/Script2 $
NumParam=$#
Param_Values=$@
n=$Param_Values
#echo "test"
#echo "$n"
for((n=n; n >= 0; n--))
do
    echo "$n"
done